apiVersion : apps/v1
kind: Deployment
metadata:
  name: k8sxiangsc-8282
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8sxiangsc-8282
  template:
    metadata:
      labels:
        app: k8sxiangsc-8282
    spec:
      containers:
        - name: k8sxiangsc-8282
          image: nginx
          ports:
          - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: rancher-webapp-svc
spec:
  type: NodePort
  selector:
    app: k8sxiangsc-8282
  ports:
    protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30080
