apiVersion : apps/v1
kind: Deployment
metadata:
  name: "k8sxiangsc-8282"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "k8sxiangsc-8282"
  template:
    metadata:
      labels:
        app: "k8sxiangsc-8282"
    spec:
      containers:
        - name: "k8sxiangsc-8282"
          image: "nginx"
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: "k8sxiangsc-8282"
    labels:
        app: "k8sxiangsc-8282"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "k8sxiangsc-8282"
